- name: Configure Consul Server
  hosts: localhost
  become: true
  gather_facts: true

  vars:
    consul_data_dir: /opt/consul
    consul_config_dir: /etc/consul.d

  tasks:
    - name: Retrieve system environment
      block:
        - name: Display current IP address
          ansible.builtin.debug:
            var: ansible_default_ipv4.address

        - name: Display current IP address
          ansible.builtin.debug:
            var: ansible_hostname

    - name: Create a consuls folders
      ansible.builtin.file:
        path: "{{ consul_config_dir }}"
        state: directory
        owner: "consul"
        group: "consul"
        mode: "0755"

    - name: Create a consuls folders
      ansible.builtin.file:
        path: "{{ consul_data_dir }}"
        state: directory
        owner: "consul"
        group: "consul"
        mode: "0755"

    - name: Add consul config file
      ansible.builtin.copy:
        content: |
          datacenter = "{{ ansible_hostname }}-dc"
          data_dir   = "{{ consul_data_dir }}"
          log_level  = "DEBUG"
          node_name  = "{{ ansible_hostname }}"
          server     = true
          client_addr = "0.0.0.0"
          bind_addr  = "{{ ansible_default_ipv4.address }}"
          ui_config  = {
            enabled = true
          }
          bootstrap_expect = 1
          retry_join = ["{{ ansible_default_ipv4.address }}"]

        dest: "{{ consul_config_dir }}/consul.hcl"
        owner: "consul"
        group: "consul"
        mode: "0644"

    - name: Start consul service
      ansible.builtin.service:
        name: consul
        state: restarted
