- name: Unseal Vault
  hosts: localhost
  gather_facts: false
  become: true
  vars:
    vault_bin_path: "/usr/bin/vault" # Replace with the actual path to your Vault binary
    vault_data_dir: /opt/vault
  vars_files:
    - "{{ vault_data_dir }}/vault.keys"
  tasks:
    - name: Vault Status
      register: vault_status
      changed_when: vault_status.rc != 2
      ignore_errors: true
      ansible.builtin.shell: "{{ vault_bin_path }} status -tls-skip-verify"
      args:
        executable: "/bin/bash"

    - name: Unseal Vault
      register: unseal_vault
      changed_when: unseal_vault.rc != 0
      ansible.builtin.shell: "{{ vault_bin_path }} operator unseal -tls-skip-verify {{ unseal_keys_b64[0] }}"
      args:
        executable: "/bin/bash"
      when: vault_status.rc == 2

    - name: Authenticate with Root Token
      register: root_token
      changed_when: root_token.rc != 0
      ansible.builtin.shell: "{{ vault_bin_path }} login -tls-skip-verify {{ root_token }}"
      args:
        executable: "/bin/bash"
      when: unseal_vault.rc == 0 # Only authenticate if initialization was successful
