- name: Install Consul GPG Key
  block:
    - name: Download Consul GPG Key
      ansible.builtin.get_url:
        url: https://apt.releases.hashicorp.com/gpg
        dest: "{{ tmp_key_location }}"
        mode: "0777"

    - name: Install GPG Key
      register: apt_key
      changed_when: apt_key.rc != 0
      ansible.builtin.shell: |
        cat {{ tmp_key_location }} | gpg --batch --yes --dearmor --quiet -o {{ key_location }}
      args:
        executable: /bin/bash

    - name: Update file permission
      ansible.builtin.file:
        path: "{{ key_location }}"
        mode: "0444"

    - name: Remove tmp file
      ansible.builtin.file:
        path: "{{ tmp_key_location }}"
        state: absent

    - name: Update APT package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install APT repository
      ansible.builtin.apt_repository:
        repo: "deb [signed-by={{ key_location }}] https://apt.releases.hashicorp.com {{ ansible_facts.distribution_release }} main"
        state: present
        filename: hashicorp.list
        update_cache: true
